import "./globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header/Header";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const ttnorms = localFont({
	src: [
		{
			path: "fonts/TTNorms-Regular.otf",
			weight: "400",
		},
		{
			path: "fonts/TTNorms-Medium.otf",
			weight: "500",
		},
		{
			path: "fonts/TTNorms-Bold.otf",
			weight: "700",
		},
	],
	variable: "--font-ttnorms",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const headersList = headers();
	// read the custom x-url header
	const header_url = headersList.get("x-url") || "";
	return (
		<html lang="en">
			<body className={`${inter.variable} ${ttnorms.className}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
